#!/bin/awk
BEGIN { FS=","; NR = NR - 1; avg = 0.0 } 
NR != 0 && NR % 5 != 0 { avg += $12 }
NR != 0 && NR % 5 == 0 { avg += $12; print $8 ", Num procs: " $2 ", Universe size:" $3 ", Operation ratio: (" $4 ":" $5 ":" $6 ":" $7 ") (UniverseSize,Total Throughput in millions): (" $2 "," (avg / 5000000.0) ")"; avg=0.0}
